services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      SA_PASSWORD: Senha@2024
      ACCEPT_EULA: Y
    ports:
      - 1343:1433
    networks:
      - database-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 3000:5672
    networks:
      - rabbitmq-network

  api:
    build:
      context: ./Web API
    container_name: api
    depends_on:
      - database
      - rabbitmq
    ports:
      - 2000:8080
    networks:
      - database-network
      - rabbitmq-network

  consumer:
    build:
      context: ./RabbitMQ Consumer
    container_name: consumer
    depends_on:
      - database
      - rabbitmq
    ports:
      - 2500:8080
    networks:
      - database-network
      - rabbitmq-network

networks:
  database-network: {}
  rabbitmq-network: {}
